### PR TITLE
Add function to output log to file

### LINKED ISSUE #23: Add function to output log to files
Add function to output log to files, additionally to STDOUT.
Refer to iRIC_LOG_FILE for the file name to output. if it is not set, log is not output to files.

### PR DESCRIPTION
**Pull request by kskinoue0612**
Close #23

### CODE REVIEW

**Comment by scharlton2** [comment]
Hi Keisuke,

I'm not getting any output or log files.  I set the following:

set IRIC_LOG_LEVEL=trace
set IRIC_LOG_FILE=xxxx.log

and ran the unittests_cgnsfile.exe file and I didn't see any log output or log files.

Let me know if I'm doing something wrong.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for reviewing the pull request.
Actually I’ve tested the code, by launching iRIC GUI after setting up
environmental variables.

I’ll check if it works with unittests_cgnsfile.exe.
Thank you,

Keisuke Inoue

2021年11月12日(金) 10:11 Scott Charlton ***@***.***>:

**Comment by kskinoue0612** [comment]
Hi Scott,

I've checked today. You are right, unittests_cgnsfile.exe does not output logs.

I'll look into the code, and tries to fix it.
Thank you,

Keisuke Inoue

**Comment by kskinoue0612** [comment]
Hi Scott,

Sorry that it took time, I've pushed another commit to fix the bug.
Please test with the new commit.

Thank you,

Keisuke

**Comment by scharlton2** [comment]
Hi Keisuke,

Don't forget the pull request I created for https://github.com/i-RIC/v3_nays2dh.

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for reminding me, I haven’t noticed the pull request. OK!

I think I’ve got too many mails last week.

Thank you,

Keisuke

2021年11月24日(水) 11:56 Scott Charlton ***@***.***>:

**Pull request merged**
